FROM registry.access.redhat.com/hi/go:1.26 AS builder
COPY . /src
WORKDIR /src
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /testserver .

FROM scratch
COPY --from=builder /testserver /testserver
ENTRYPOINT ["/testserver"]
